// Extension for Chrome Browser - Magic Actions for YouTube™ - CHROMEACTIONS.COM - Copyright 2015 Vlad and Serge Strukoff - All Rights Reserved
chrome.runtime.onStartup.addListener(function(){});
(function(){function l(b){var e={ver:m,nv:3,uid:"",mwvc:!0,color:"yellow",mwvct:0,mwvci:2,gap:10,hq:!0,hqi:"large",pause:!1,plist:!1,buf:!1,buf1:!1,loop:!1,hide:!1,ha:!1,anns:!0,cin:!0,cina:!1,cini:2,cinf:!1,cinc:1,cins:"",pt:!1,pti:0,ww:!1,wide:!1,h0:!1,h1:!1,h2:!1,h3:!1,h4:!1,h5:!1,h6:!1,h7:!1,h8:!1,a0:!0,a1:!1,a2:!1,a3:!1,a4:!0,a5:!1,ui:0,c0:!1,c1:!1,c2:!1,c3:!1,c4:!1,f0:!0,mrl:!0};a=b;if(void 0===a||null===a||"object"!==typeof a||void 0===a.ver)a={nv:3,uid:s()};for(var c in e)void 0===a[c]&&(a[c]=
e[c]);for(c in a)void 0===e[c]&&(delete a[c],chrome.storage.local.remove(c));for(c in a)typeof a[c]!==typeof e[c]&&(a[c]=e[c]);t();document.cookie&&-1<document.cookie.indexOf("s=1")?(k=parseInt(localStorage.st),u()):(document.cookie="s=1; expires=0; path=/",localStorage.st=k,u(),3==a.nv?v(1):a.ver!==m?(b=k,e=b+18144E5,a.nv=Math.floor(Math.random()*(e-b+1))+b,a.ver=m,h(),setTimeout(n,2877)):0<a.nv&&a.nv<k&&v())}function u(){chrome.runtime.onMessage.addListener(z);a.a0&&a.a3&&A();setTimeout(n,2333)}
function v(b){chrome.tabs.create({url:"http://www.chromeactions.com"});b?(a.nv=0,h(),p({ea:"install"}),chrome.tabs.create({url:"http://www.hotcleaner.com/clickclean/install-magic.html"})):(a.nv=1,h(),p({ea:"update"}),w());setTimeout(n,2100)}function t(b){function e(b){return(Array(8).join("0")+b.toString(16)).slice(-8)}b=chrome.runtime.getURL("");var c=0,d=0,f=0,g="red LightPink orange lime GreenYellow yellow gold DodgerBlue aqua magenta DeepPink white".split(" ").indexOf(a.color),h="highres hd2880 hd2160 hd1440 hd1080 hd720 large medium small tiny".split(" ").indexOf(a.hqi),
c=c|a.h0<<19,c=c|a.h1<<18,c=c|a.h2<<17,c=c|a.h3<<16,c=c|a.h4<<15,c=c|a.h5<<14,c=c|a.h6<<13,c=c|a.h7<<12,c=c|a.h8<<11,c=c|a.a0<<10,c=c|a.a1<<9,c=c|a.a2<<8,c=c|a.a3<<7,c=c|a.a4<<6,c=c|a.a5<<5,c=c|a.c0<<4,c=c|a.c1<<3,c=c|a.c2<<2,c=c|a.c3<<1,c=c|a.c4,d=d|a.ui<<25,d=d|a.wide<<24,d=d|a.ww<<23,d=d|a.mwvc<<22,d=d|(0>g?4:g)<<18|a.mwvct<<17,d=d|a.mwvci<<15,d=d|a.gap<<10,d=d|a.pause<<9,d=d|a.plist<<8,d=d|a.buf<<7,d=d|a.buf1<<6,d=d|a.loop<<5,d=d|a.hide<<4,d=d|a.ha<<3,d=d|a.anns<<2,d=d|a.pt<<1,d=d|a.pti,f=f|a.mrl<<
18,f=f|a.f0<<17,f=f|a.hq<<16,f=f|(0>h?5:h)<<12|a.cin<<11,f=f|a.cina<<10,f=f|a.cini<<8,f=f|a.cinf<<7,f=f|(63<a.cinc?63:a.cinc);b="0"+e(c)+e(d)+e(f)+b+(62<a.cinc?a.cins:"");q='var e=document.createEvent("CustomEvent");e.initCustomEvent("mafy",!1,!1,"'+b+'");window.dispatchEvent(e);if(window.sessionStorage)window.sessionStorage.mafy="'+b+'"'}function h(){a.a0&&a.a4||(a.ui=0);try{chrome.storage.local.set(a)}catch(b){x(b,1)}try{localStorage.setItem("opt",JSON.stringify(a))}catch(e){x(e,1)}t(1);chrome.tabs.query({windowType:"normal",
url:"*://*.youtube.com/*",status:"complete"},function(b){for(var a=0,e=b.length;a<e;a++)chrome.tabs.executeScript(b[a].id,{code:q.replace('"0','"1')})})}function z(b,e,c){32==b&&(chrome.tabs.executeScript(e.tab.id,{code:q,runAt:"document_start"}),chrome.pageAction.show(e.tab.id));try{b=JSON.parse(b)}catch(d){return}0==b.id?c({opt:a,url:e.tab.url}):1==b.id?p(b.ga):2==b.id?chrome.tabs.create({url:b.url}):3==b.id?(a=b.opt,h()):4==b.id?(a[b.name]=b.value,h()):5==b.id?c({value:a[b.name]}):6==b.id?B(b.v):
7==b.id?w():9==b.id?c(y):11==b.id&&chrome.windows.update(e.tab.windowId,{state:b.v?"fullscreen":"maximized"});return!0}function B(b){chrome.windows.getLastFocused({populate:!1},function(a){y={w:b[0],h:b[1],pic:b[2],vid:b[3],lic:b[4],t:b[5]};chrome.tabs.query({url:"http://www.chromeactions.com/capture-snapshot-video-frames.html"},function(b){b&&b.length?chrome.tabs.update(b[0].id,{active:!0},function(){chrome.tabs.executeScript(b[0].id,{file:"cap6895.js"})}):chrome.tabs.create({active:!0,url:"http://www.chromeactions.com/capture-snapshot-video-frames.html"})})})}
function w(){function b(){chrome.tabs.get(a,function(d){"complete"==d.status?0!=d.title.indexOf("Magic")&&chrome.tabs.update(a,{url:c}):setTimeout(b,1E3)})}var a,c="opt.html?s=689"+(new Date).getDate(),d=navigator.onLine?"http://www.chromeactions.com/magic-options.html":c;chrome.tabs.query({url:d},function(c){c&&c.length?chrome.tabs.update(c[0].id,{active:!0},function(b){chrome.windows.update(b.windowId,{focused:!0})}):chrome.tabs.create({url:d,active:!0},function(c){a=c.id;setTimeout(b,3E3)})})}
function x(b,a){console.log("Magic: "+["Could't read preferences.","Could't write preferences."][a]+" "+b.name+": "+b.message)}function C(b,a){if(7840==b.menuItemId){var c="http://www.youtube.com/results?search_query="+encodeURIComponent(b.selectionText);0==a.url.indexOf("http://www.youtube.com/")?chrome.tabs.update({url:c}):chrome.tabs.create({url:c,selected:!0})}}function A(){chrome.contextMenus.create({id:"7840",title:"Search YouTube for %s",contexts:["selection"]},function(){chrome.contextMenus.onClicked.addListener(C)})}
function n(){r("GET","manifest.json",null,"text",function(b){if(b){try{b=JSON.parse(b)}catch(a){return}r("GET",b.update_url+"?x=id%3Dabjcfabbhafbcdfjoecdgepllmpfceif%26v%3D"+b.version+"%26uc&_="+(new Date).getTime(),null,"text",function(b){})}})}function p(b){var e=b.ec?b.ec:"app",c=b.ea?b.ea:"unk";b=b.el?b.el:"mafy 6.8.9.5";a.uid||(a.uid=s());r("POST","http://www.google-analytics.com/collect","v=1&tid=UA-326771-7&cid="+a.uid+"&t=event&ec="+e+"&ea="+c+"&el="+b,"text",function(){})}function r(b,a,
c,d,f){var g=new XMLHttpRequest;g.open(b,a,!0);d&&(g.responseType=d);g.onload=function(b){200==this.status?f(this.response):f(null)};g.onerror=function(){f(null)};g.onabort=function(){f(null)};g.send(c)}function s(){var b=Math.random,a=(4294967296*b()>>>0).toString(16),c=((4294967296*b()&4294922239|16384)>>>0).toString(16),d=((4294967296*b()&3221225471|2147483648)>>>0).toString(16),b=(4294967296*b()>>>0).toString(16);8>a.length&&(a=("0000000"+a).slice(-8));8>c.length&&(c=("0000000"+c).slice(-8));
8>d.length&&(d=("0000000"+d).slice(-8));8>b.length&&(b=("0000000"+b).slice(-8));return[a,c.slice(0,4),c.slice(4),d.slice(0,4),d.slice(4)+b].join("-")}var m="6.8.9.5",k=Date.now(),y,a,q;chrome.storage.local.get(null,function(a){if(chrome.runtime.lastError)if(a=localStorage.getItem("opt"),void 0===a)l();else{try{a=JSON.parse(a)}catch(e){a=void 0}l(a)}else l(a)})})();
