// Extension for Chrome Browser - Magic Actions for YouTube™ - CHROMEACTIONS.COM - Copyright 2015 Vlad and Serge Strukoff - All Rights Reserved
(function(){function n(){document&&"complete"==document.readyState?d.c0&&(d.c4&&p(),d.c1&&document.body.addEventListener("mouseover",u,!0)):setTimeout(n,250)}function r(){var a=document.getElementById("j782k77h"),b;a||(a=document.createElement("style"),a.setAttribute("type","text/css"),a.id="j782k77h",document.documentElement.appendChild(a),b=a.sheet,b.disabled=d.a0&&d.a4&&d.ui?!1:!0,b.insertRule("body *{color:#909090!important}",0),b.insertRule("div,div > span{background-color:#1E1E1E!important;border-color:#333!important}",
1),b.insertRule("a{color:#656565!important}",2),b.insertRule("a:hover,a > span,div[role=button] > span{color:#6783ab!important}",3),b.insertRule("[aria-label='Posting options']{background:url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABUAAAAVCAYAAACpF6WWAAAAS0lEQVQ4y2NgGAWjYIiD////t//HDqZRYijj////l6AZuPH////MlLqW7f///3uhBp74//8/F7WCgf/////b/v//Lz2aKEbBKMADAMppT6HBpHJKAAAAAElFTkSuQmCC') center no-repeat!important}",4),b.insertRule("span[role=listitem] *{color:#fff!important;background-color:transparent!important}",
5),b.insertRule("[role=checkbox],[role=tooltip] div,.Mga,.Jea{border:0!important}",6),b.insertRule("[role=checkbox] > div{border:1px solid #333!important}",7),b.insertRule("[aria-checked=true] > div{box-shadow:inset 0 0 0 3px #101010!important;background:#4e4e4e!important}",8),b.insertRule("span.r0,.g-h-f-p-Ov{background:none!important}",9),b.insertRule(".MJa,.LJa{-webkit-filter:invert(100%)!important}",10));a.sheet.disabled=d.a0&&d.a4&&d.ui?!1:!0}function p(){c(window,"mouseover");var a=document.body.querySelector('div[role="listbox"]');
if(a){document.documentElement.style.visibility="hidden";c(a,"mouseover");c(a,"mousedown");c(a,"mouseup");if(a=document.body.querySelector('div[role="menu"]'))if(a=a.lastElementChild.firstElementChild)c(a,"mouseover"),c(a,"mousedown"),c(a,"mouseup"),c(a,"mousedown"),c(a,"mouseup");document.documentElement.style.visibility=""}else setTimeout(p,500)}function c(a,b){var v=new MouseEvent(b,{bubbles:!0,cancelable:!0,view:window});a.dispatchEvent(v)}function u(a){"img"==a.target.localName&&24<a.target.width&&
(a.target.addEventListener("mouseout",s,!1),w(a))}function w(a){e&&(e=clearTimeout(e));var b=a.target;b.removeAttribute("title");e=setTimeout(function(){var a;if((a=b)&&void 0!=a){var g=0,d=0;if(a.offsetParent){do g+=a.offsetLeft,d+=a.offsetTop;while(a=a.offsetParent)}a=[g,d]}else a=[0,0];var c=a[0];a=a[1];var k=b.offsetWidth,g=b.offsetHeight,h,d=b.src.replace(/s\d+-c-k/,"s256-c-k");300>c?(h=c+k+20,c="magic-tip-left"):(h=c-256-20,c="magic-tip-right");g=a-parseInt((256-g)/2)-5;k=128;0>g&&(k+=g,g=0);
a=h;var k=k+"px",d="url("+d+") center center/100% auto no-repeat",e;if(f)h=f.firstElementChild,e=f.lastElementChild;else{f=document.createElement("div");h=document.createElement("div");e=document.createElement("iframe");f.className="magic-tip";for(var n=e,q=["scrolling","no","frameborder",0],l=0,p=q.length;l<p;l+=2)n.setAttribute(q[l],q[l+1]);f.appendChild(h);f.appendChild(e);document.body.appendChild(f)}t(f,["top",g+"px","left",a+"px","height","256px"],1);t(e,["width","256px","height","256px","background",
d,"display","block"],1);c?(h.style.setProperty("display",""),h.className=c,k&&h.style.setProperty("top",k,m)):h.style.setProperty("display","none",m);f.style.setProperty("display","block",m)},500);a.stopPropagation()}function s(a){a.target.removeEventListener("mouseout",s,!1);e&&(e=clearTimeout(e));f&&f.style.setProperty("display","none",m)}function t(a,b,d){if(a){var c=0,e=b.length;for(d=d?m:null;c<e;c+=2)a.style.setProperty(b[c],b[c+1],d)}}var d;chrome.runtime.getURL("");var f,e,m="important";chrome.runtime.sendMessage('{"id":0}',
function(a){a&&a.opt&&(d=a.opt,r(),a=document.getElementById("s77n549g"),a||(a=document.createElement("style"),a.setAttribute("type","text/css"),a.id="s77n549g",document.documentElement.appendChild(a),a=a.sheet,a.insertRule(".magic-tip{z-index:2147483648;position:absolute;background-color:#333;border:7px solid #333;border-radius:7px}",0),a.insertRule(".magic-tip-right{position:absolute;top:50%;right:-17px;margin-top:-10px;width:0;height:0;border-style:solid;border-width:10px 0 10px 10px;border-color:transparent #333!important}",
1),a.insertRule(".magic-tip-left{position:absolute;top:50%;left:-17px;margin-top:-10px;width:0;height:0;border-style:solid;border-width:10px 10px 10px 0;border-color:transparent #333!important}",2),a.insertRule("a.magic-flag{width:16px;height:11px;display:inline-block;margin-right:7px;cursor:pointer;background-repeat:no-repeat}",3),a.insertRule("a.magic-flag:hover{-webkit-transform:scale(2.0)}",4)),n())});window.addEventListener("message",function(a){var b=0;try{b=JSON.parse(a.data)}catch(c){return}689==
b.id&&(d=b.opt,r())},!1)})();
