try{
'use strict';var l,m=this,aa=function(a){a.M=function(){return a.S?a.S:a.S=new a}},ba=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&
"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},n=function(a){return"array"==ba(a)},ca=function(a){var b=ba(a);return"array"==b||"object"==b&&"number"==typeof a.length},q=function(a){return"string"==typeof a},da=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},r="closure_uid_"+(1E9*Math.random()>>>0),ea=0,fa=function(a,b,c){return a.call.apply(a.bind,
arguments)},ga=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},u=function(a,b,c){u=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?fa:ga;return u.apply(null,arguments)},ha=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=
c.slice();b.push.apply(b,arguments);return a.apply(this,b)}},v=Date.now||function(){return+new Date},w=function(a,b){function c(){}c.prototype=b.prototype;a.H=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.w=function(a,c,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[c].apply(a,g)}};
var x=function(){this.h=this.h;this.g=this.g};x.prototype.h=!1;x.prototype.P=function(){this.h||(this.h=!0,this.C())};var ia=function(a,b){a.h?b.call(void 0):(a.g||(a.g=[]),a.g.push(b))};x.prototype.C=function(){if(this.g)for(;this.g.length;)this.g.shift()()};var ja=function(a){a&&"function"==typeof a.P&&a.P()};
var y=function(a,b){this.type=a;this.a=this.target=b;this.U=!0};y.prototype.g=function(){this.U=!1};var ka=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},z=function(a){return null==a?"":String(a)},la=function(a,b){return a<b?-1:a>b?1:0};var ma=function(a){y.call(this,a);this.h=0;this.c=null;this.m=this.o="";this.s=0;this.i=""};w(ma,y);var na=function(a,b,c,d,e){var f=new ma("clip_changed");f.c=a;f.h=b;f.o=c;f.m=d;e&&(f.s=e.i,f.i=e.B());return f};ma.prototype.F=function(){return z(this.c&&this.c.B()||null)};
var A=Array.prototype,oa=function(a,b,c){A.forEach.call(a,b,c)},pa=function(a,b){return A.map.call(a,b,void 0)},qa=function(a){return A.concat.apply(A,arguments)},ra=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},sa=function(a,b){return a>b?1:a<b?-1:0};
var ta=m.JSON.stringify;var ua=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)},va=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b},wa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),xa=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<wa.length;f++)c=wa[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}},ya=function(a){var b=arguments.length;if(1==b&&n(arguments[0]))return ya.apply(null, arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};
var B=function(){},C=function(a,b,c,d){a.a=null;b||(b=[]);a.m=void 0;a.i=-1;a.c=b;a:{if(a.c.length){b=a.c.length-1;var e=a.c[b];if(e&&"object"==typeof e&&!n(e)){a.h=b-a.i;a.g=e;break a}}-1<c?(a.h=c,a.g=null):a.h=Number.MAX_VALUE}if(d)for(c=0;c<d.length;c++)b=d[c],b<a.h?(b+=a.i,a.c[b]=a.c[b]||za):a.g[b]=a.g[b]||za},za=[],D=function(a,b){if(b<a.h){var c=b+a.i,d=a.c[c];return d===za?a.c[c]=[]:d}d=a.g[b];return d===za?a.g[b]=[]:d},E=function(a,b,c){b<a.h?a.c[b+a.i]=c:a.g[b]=c},F=function(a,b,c){a.a||
(a.a={});if(!a.a[c]){var d=D(a,c);d&&(a.a[c]=new b(d))}return a.a[c]},G=function(a,b,c){a.a||(a.a={});var d=c?c.c:c;a.a[b]=c;E(a,b,d)};B.prototype.l=function(){return m.JSON&&m.JSON.stringify?m.JSON.stringify(this.c):ta(this.c)};B.prototype.toString=function(){return this.c.toString()};
B.prototype.X=function(){var a=Aa;if(this.g){this.a||(this.a={});var b=a.c;if(a.g){if(a.a)return this.a[b]||(this.a[b]=pa(this.g[b]||[],function(b){return new a.a(b)})),this.a[b]}else if(a.a)return!this.a[b]&&this.g[b]&&(this.a[b]=new a.a(this.g[b])),this.a[b];return this.g[b]}};var Ba=function(a){var b;if(n(a)){for(var c=Array(a.length),d=0;d<a.length;d++)null!=(b=a[d])&&(c[d]="object"==typeof b?Ba(b):b);return c}c={};for(d in a)null!=(b=a[d])&&(c[d]="object"==typeof b?Ba(b):b);return c};
var Da=function(a){C(this,a,-1,Ca)};w(Da,B);var Ca=[3];Da.prototype.getTitle=function(){return D(this,2)};Da.prototype.setTitle=function(a){E(this,2,a)};var Ea=function(a){this.a=a||new Da};Ea.prototype.setTitle=function(a){this.a.setTitle(a)};Ea.prototype.l=function(){return this.a.l()};var Fa=function(a){C(this,a,-1,null)};w(Fa,B);var I=function(a){return F(a,H,2)},H=function(a){C(this,a,-1,null)};w(H,B);var Ga=function(a){return D(a,1)};var J=function(a){C(this,a,-1,null)};w(J,B);J.prototype.B=function(){return D(this,1)};var Ha=function(a){C(this,a,-1,null)};w(Ha,B);Ha.prototype.getTitle=function(){return D(this,1)};Ha.prototype.setTitle=function(a){E(this,1,a)};var Ia=function(a){C(this,a,-1,null)};w(Ia,B);var Ja=function(a){C(this,a,-1,null)};w(Ja,B);var La=function(a){C(this,a,22,Ka)};w(La,B);var Ka=[3];La.prototype.F=function(){return F(this,J,1)};var Ma=function(a){C(this,a,-1,null)};w(Ma,B);var Na=function(a){this.a=a||new Ma};Na.prototype.l=function(){return this.a.l()};var Oa;a:{var Pa=m.navigator;if(Pa){var Qa=Pa.userAgent;if(Qa){Oa=Qa;break a}}Oa=""};var Ra="",Sa=/WebKit\/(\S+)/.exec(Oa);Sa&&(Ra=Sa?Sa[1]:"");
var Ta=Ra,Ua={},Va=function(){if(!Ua["528"]){for(var a=0,b=ka(String(Ta)).split("."),c=ka("528").split("."),d=Math.max(b.length,c.length),e=0;0==a&&e<d;e++){var f=b[e]||"",g=c[e]||"",h=/(\d*)(\D*)/g,k=/(\d*)(\D*)/g;do{var t=h.exec(f)||["","",""],p=k.exec(g)||["","",""];if(0==t[0].length&&0==p[0].length)break;a=la(0==t[1].length?0:parseInt(t[1],10),0==p[1].length?0:parseInt(p[1],10))||la(0==t[2].length,0==p[2].length)||la(t[2],p[2])}while(0==a)}Ua["528"]=0<=a}};
var Wa=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/,Ya=function(a){if(Xa){Xa=!1;var b=m.location;if(b){var c=b.href;if(c&&(c=(c=Ya(c)[3]||null)?decodeURI(c):c)&&c!=b.hostname)throw Xa=!0,Error();}}return a.match(Wa)},Xa=!0,Za=function(a,b){for(var c=a.split("&"),d=0;d<c.length;d++){var e=c[d].indexOf("="),f=null,g=null;0<=e?(f=c[d].substring(0,e),g=c[d].substring(e+1)):f=c[d];b(f,g?decodeURIComponent(g.replace(/\+/g," ")):"")}};
var $a="StopIteration"in m?m.StopIteration:{message:"StopIteration",stack:""},ab=function(){};ab.prototype.a=function(){throw $a;};ab.prototype.K=function(){return this};var K=function(a,b){this.c={};this.a=[];this.h=this.g=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){if(a instanceof K)d=a.G(),c=a.v();else{var c=[],e=0;for(d in a)c[e++]=d;d=c;c=va(a)}for(e=0;e<d.length;e++)this.set(d[e],c[e])}};K.prototype.v=function(){bb(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.c[this.a[b]]);return a};K.prototype.G=function(){bb(this);return this.a.concat()};
K.prototype.remove=function(a){return L(this.c,a)?(delete this.c[a],this.g--,this.h++,this.a.length>2*this.g&&bb(this),!0):!1};var bb=function(a){if(a.g!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];L(a.c,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.g!=a.a.length){for(var e={},c=b=0;b<a.a.length;)d=a.a[b],L(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};l=K.prototype;l.get=function(a,b){return L(this.c,a)?this.c[a]:b};
l.set=function(a,b){L(this.c,a)||(this.g++,this.a.push(a),this.h++);this.c[a]=b};l.forEach=function(a,b){for(var c=this.G(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};l.clone=function(){return new K(this)};l.K=function(a){bb(this);var b=0,c=this.h,d=this,e=new ab;e.a=function(){if(c!=d.h)throw Error("The map has changed since the iterator was created");if(b>=d.a.length)throw $a;var e=d.a[b++];return a?e:d.c[e]};return e}; var L=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
var cb=function(a){if("function"==typeof a.v)return a.v();if(q(a))return a.split("");if(ca(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return va(a)};var M=function(a,b){this.g=this.s=this.c="";this.o=null;this.i=this.m="";this.a=!1;var c;a instanceof M?(this.a=void 0!==b?b:a.a,db(this,a.c),this.s=a.s,this.g=a.g,eb(this,a.o),this.m=a.m,fb(this,a.h.clone()),this.i=a.i):a&&(c=Ya(String(a)))?(this.a=!!b,db(this,c[1]||"",!0),this.s=gb(c[2]||""),this.g=gb(c[3]||"",!0),eb(this,c[4]),this.m=gb(c[5]||"",!0),fb(this,c[6]||"",!0),this.i=gb(c[7]||"")):(this.a=!!b,this.h=new N(null,0,this.a))};
M.prototype.toString=function(){var a=[],b=this.c;b&&a.push(hb(b,ib,!0),":");if(b=this.g){a.push("//");var c=this.s;c&&a.push(hb(c,ib,!0),"@");a.push(encodeURIComponent(String(b)).replace(/%25([0-9a-fA-F]{2})/g,"%$1"));b=this.o;null!=b&&a.push(":",String(b))}if(b=this.m)this.g&&"/"!=b.charAt(0)&&a.push("/"),a.push(hb(b,"/"==b.charAt(0)?jb:kb,!0));(b=this.h.toString())&&a.push("?",b);(b=this.i)&&a.push("#",hb(b,lb));return a.join("")};M.prototype.clone=function(){return new M(this)};
var db=function(a,b,c){a.c=c?gb(b,!0):b;a.c&&(a.c=a.c.replace(/:$/,""))},eb=function(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.o=b}else a.o=null},fb=function(a,b,c){b instanceof N?(a.h=b,mb(a.h,a.a)):(c||(b=hb(b,nb)),a.h=new N(b,0,a.a))},ob=function(a){a instanceof M?a.clone():new M(a,void 0)},gb=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},hb=function(a,b,c){return q(a)?(a=encodeURI(a).replace(b,pb),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,
"%$1")),a):null},pb=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},ib=/[#\/\?@]/g,kb=/[\#\?:]/g,jb=/[\#\?]/g,nb=/[\#\?@]/g,lb=/#/g,N=function(a,b,c){this.g=this.a=null;this.c=a||null;this.h=!!c},O=function(a){a.a||(a.a=new K,a.g=0,a.c&&Za(a.c,function(b,c){var d=decodeURIComponent(b.replace(/\+/g," "));O(a);a.c=null;var d=P(a,d),e=a.a.get(d);e||a.a.set(d,e=[]);e.push(c);a.g++}))};
N.prototype.remove=function(a){O(this);a=P(this,a);return L(this.a.c,a)?(this.c=null,this.g-=this.a.get(a).length,this.a.remove(a)):!1};var qb=function(a,b){O(a);b=P(a,b);return L(a.a.c,b)};l=N.prototype;l.G=function(){O(this);for(var a=this.a.v(),b=this.a.G(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};l.v=function(a){O(this);var b=[];if(q(a))qb(this,a)&&(b=qa(b,this.a.get(P(this,a))));else{a=this.a.v();for(var c=0;c<a.length;c++)b=qa(b,a[c])}return b};
l.set=function(a,b){O(this);this.c=null;a=P(this,a);qb(this,a)&&(this.g-=this.a.get(a).length);this.a.set(a,[b]);this.g++;return this};l.get=function(a,b){var c=a?this.v(a):[];return 0<c.length?String(c[0]):b};l.toString=function(){if(this.c)return this.c;if(!this.a)return"";for(var a=[],b=this.a.G(),c=0;c<b.length;c++)for(var d=b[c],e=encodeURIComponent(String(d)),d=this.v(d),f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+encodeURIComponent(String(d[f])));a.push(g)}return this.c=a.join("&")};
l.clone=function(){var a=new N;a.c=this.c;this.a&&(a.a=this.a.clone(),a.g=this.g);return a};var P=function(a,b){var c=String(b);a.h&&(c=c.toLowerCase());return c},mb=function(a,b){b&&!a.h&&(O(a),a.c=null,a.a.forEach(function(a,b){var e=b.toLowerCase();b!=e&&(this.remove(b),this.remove(e),0<a.length&&(this.c=null,this.a.set(P(this,e),ra(a)),this.g+=a.length))},a));a.h=b};
var rb=function(a){this.a=a||new Ha;a=D(this.a,3);E(this.a,3,a)};rb.prototype.getTitle=function(){return z(this.a.getTitle())};rb.prototype.setTitle=function(a){this.a.setTitle(a)};rb.prototype.l=function(){return this.a.l()};ya("area base br col command embed hr img input keygen link meta param source track wbr".split(" "));var sb=function(){this.c="";this.a=null},tb=function(a){var b=new sb;b.c=a;b.a=0};tb("<!DOCTYPE html>");tb("");var vb=function(a){this.a=new K;if(a){a=cb(a);for(var b=a.length,c=0;c<b;c++){var d=a[c];this.a.set(ub(d),d)}}},ub=function(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+(a[r]||(a[r]=++ea)):b.substr(0,1)+a};l=vb.prototype;l.removeAll=function(a){a=cb(a);for(var b=a.length,c=0;c<b;c++)this.remove(a[c])};l.remove=function(a){return this.a.remove(ub(a))};l.v=function(){return this.a.v()};l.clone=function(){return new vb(this)};l.K=function(){return this.a.K(!1)};
var xb=function(a,b,c,d,e){"number"==typeof e||wb++;this.g=d||v();this.h=a;this.i=b;this.c=c;delete this.a};xb.prototype.a=null;var wb=0;xb.prototype.getMessage=function(){return this.i};var yb=function(a){this.h=a;this.c=this.g=this.a=null},Q=function(a,b){this.name=a;this.value=b};Q.prototype.toString=function(){return this.name};var zb=new Q("SHOUT",1200),Ab=new Q("SEVERE",1E3),Bb=new Q("WARNING",900),Cb=new Q("INFO",800),Db=new Q("CONFIG",700);yb.prototype.getChildren=function(){this.c||(this.c={});return this.c};var Eb=function(a){return a.g?a.g:a.a?Eb(a.a):null};
yb.prototype.log=function(a,b,c){if(a.value>=Eb(this).value)for("function"==ba(b)&&(b=b()),a=new xb(a,String(b),this.h),c&&(a.a=c),c="log:"+a.getMessage(),m.console&&(m.console.timeStamp?m.console.timeStamp(c):m.console.markTimeline&&m.console.markTimeline(c)),m.msWriteProfilerMark&&m.msWriteProfilerMark(c),c=this;c;)c=c.a}; var Fb={},Gb=null,Hb=function(){Gb||(Gb=new yb(""),Fb[""]=Gb,Gb.g=Db)},Ib=function(a){Hb();var b;if(!(b=Fb[a])){b=new yb(a);var c=a.lastIndexOf("."),d=a.substr(c+1),c=Ib(a.substr(0,c));c.getChildren()[d]=b;b.a=c;Fb[a]=b}return b};
Ib("gws.collections.models.IndexedClips");Ib("gws.collections.models.IndexedFolios");var Jb=function(){};aa(Jb);var Kb={0:"c_",1:"f_",2:"d_",3:"g_",4:"lc_",5:"lf_"},Lb=function(a){return Kb[a]+(839808*a+Math.floor(839808*Math.random())).toString(36)+v().toString(36)};var Mb=function(a,b,c){y.call(this,c||"TRANSACTION_COMMIT");this.i=a||0;(a=b)||(Jb.M(),a=Lb(2));this.h=a;this.c=[];this.m=[]};w(Mb,y);var Ob=function(a,b,c){a.c.push(b);a.m.push(c);Nb(c,b)};Mb.prototype.B=function(){return this.h};Va();Va();var Pb=function(a,b){y.call(this,a?a.type:"");this.c=this.state=this.a=this.target=null;a&&(this.type=a.type,this.target=a.target||a.srcElement,this.a=b,this.state=a.state,this.c=a,a.defaultPrevented&&this.g())};w(Pb,y);Pb.prototype.g=function(){Pb.H.g.call(this);var a=this.c;a.preventDefault?a.preventDefault():a.returnValue=!1};
var Qb="closure_listenable_"+(1E6*Math.random()|0),Rb=0;var Sb=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.L=!!d;this.J=e;this.R=++Rb;this.removed=this.I=!1},Tb=function(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.J=null};var Ub=function(a){this.src=a;this.a={};this.c=0},Wb=function(a,b,c,d,e){var f=b.toString();b=a.a[f];b||(b=a.a[f]=[],a.c++);var g=Vb(b,c,d,e);-1<g?(a=b[g],a.I=!1):(a=new Sb(c,a.src,f,!!d,e),a.I=!1,b.push(a));return a};Ub.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=Vb(e,b,c,d);return-1<b?(Tb(e[b]),A.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.c--),!0):!1};
var Xb=function(a,b){var c=b.type,d;if(d=c in a.a){d=a.a[c];var e;e=A.indexOf.call(d,b,void 0);var f;(f=0<=e)&&A.splice.call(d,e,1);d=f}d&&(Tb(b),0==a.a[c].length&&(delete a.a[c],a.c--))};Ub.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,Tb(d[e]);delete this.a[c];this.c--}return b}; var Yb=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=Vb(a,c,d,e));return-1<b?a[b]:null},Vb=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.listener==b&&f.L==!!c&&f.J==d)return e}return-1};
var Zb="closure_lm_"+(1E6*Math.random()|0),$b={},ac=0,bc=function(a,b,c,d,e){if(n(b)){for(var f=0;f<b.length;f++)bc(a,b[f],c,d,e);return null}c=cc(c);if(a&&a[Qb])a=a.listen(b,c,d,e);else{if(!b)throw Error("Invalid event type");var f=!!d,g=dc(a);g||(a[Zb]=g=new Ub(a));c=Wb(g,b,c,d,e);if(!c.proxy){d=ec();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)a.addEventListener(b.toString(),d,f);else if(a.attachEvent)a.attachEvent(fc(b.toString()),d);else throw Error("addEventListener and attachEvent are unavailable.");
ac++}a=c}return a},ec=function(){var a=gc,b=function(c){return a.call(b.src,b.listener,c)};return b},hc=function(a,b,c,d,e){if(n(b))for(var f=0;f<b.length;f++)hc(a,b[f],c,d,e);else c=cc(c),a&&a[Qb]?a.unlisten(b,c,d,e):a&&(a=dc(a))&&(b=Yb(a,b,c,!!d,e))&&ic(b)},ic=function(a){if("number"!=typeof a&&a&&!a.removed){var b=a.src;if(b&&b[Qb])Xb(b.A,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.L):b.detachEvent&&b.detachEvent(fc(c),d);ac--;(c=dc(b))?(Xb(c,a),0==c.c&&(c.src=
null,b[Zb]=null)):Tb(a)}}},fc=function(a){return a in $b?$b[a]:$b[a]="on"+a},gc=function(a,b){var c;if(a.removed)c=!0;else{c=new Pb(b,this);var d=a.listener,e=a.J||a.src;a.I&&ic(a);c=d.call(e,c)}return c},dc=function(a){a=a[Zb];return a instanceof Ub?a:null},jc="__closure_events_fn_"+(1E9*Math.random()>>>0),cc=function(a){if("function"==ba(a))return a;a[jc]||(a[jc]=function(b){return a.handleEvent(b)});return a[jc]};
var R=function(){x.call(this);this.A=new Ub(this);this.Y=this;this.m=null};w(R,x);R.prototype[Qb]=!0;R.prototype.removeEventListener=function(a,b,c,d){hc(this,a,b,c,d)};
var Nb=function(a,b){var c,d=a.m;if(d)for(c=[];d;d=d.m)c.push(d);var d=a.Y,e=b,f=e.type||e;if(q(e))e=new y(e,d);else if(e instanceof y)e.target=e.target||d;else{var g=e,e=new y(f,d);xa(e,g)}var g=!0,h;if(c)for(var k=c.length-1;0<=k;k--)h=e.a=c[k],g=kc(h,f,!0,e)&&g;h=e.a=d;g=kc(h,f,!0,e)&&g;g=kc(h,f,!1,e)&&g;if(c)for(k=0;k<c.length;k++)h=e.a=c[k],g=kc(h,f,!1,e)&&g};R.prototype.C=function(){R.H.C.call(this);this.A&&this.A.removeAll(void 0);this.m=null};
R.prototype.listen=function(a,b,c,d){return Wb(this.A,String(a),b,c,d)};R.prototype.unlisten=function(a,b,c,d){return this.A.remove(String(a),b,c,d)};var kc=function(a,b,c,d){b=a.A.a[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.removed&&g.L==c){var h=g.listener,k=g.J||g.src;g.I&&Xb(a.A,g);e=!1!==h.call(k,d)&&e}}return e&&0!=d.U};
var lc=function(){R.call(this)};w(lc,R);var mc=function(a){R.call(this);this.a=a};w(mc,lc);mc.prototype.B=function(){return this.a.F()?z(this.a.F().B()):""};mc.prototype.l=function(){return this.a.l()};var nc=function(a){x.call(this);this.c=a;this.a={}};w(nc,x);var oc=[];l=nc.prototype;l.listen=function(a,b,c,d){n(b)||(b&&(oc[0]=b.toString()),b=oc);for(var e=0;e<b.length;e++){var f=bc(a,b[e],c||this.handleEvent,d||!1,this.c||this);if(!f)break;this.a[f.R]=f}return this};
l.unlisten=function(a,b,c,d,e){if(n(b))for(var f=0;f<b.length;f++)this.unlisten(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.c||this,c=cc(c),d=!!d,b=a&&a[Qb]?Yb(a.A,String(b),c,d,e):a?(a=dc(a))?Yb(a,b,c,d,e):null:null,b&&(ic(b),delete this.a[b.R]);return this};l.removeAll=function(){ua(this.a,function(a,b){this.a.hasOwnProperty(b)&&ic(a)},this);this.a={}};l.C=function(){nc.H.C.call(this);this.removeAll()};l.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};
var qc=function(a){this.a=a||new Fa;if(!I(this.a)){a=this.a;var b=new H;G(a,2,b)}F(this.a,H,3)||(a=this.a,b=new H,G(a,3,b));this.c=new M(z(Ga(I(this.a))));new M(pc(this))},pc=function(a){return z(Ga(F(a.a,H,3))).replace(/^\/\//,"https://")};qc.prototype.l=function(){return this.a.l()};
var rc=function(a){this.a=a||new Ia};rc.prototype.l=function(){return this.a.l()};var sc=function(a){this.a=a||new Ja};sc.prototype.l=function(){return this.a.l()};var tc=function(a){C(this,a,-1,null)};w(tc,B);var Aa=new function(){this.c=71309500;this.a=tc;this.g=0}(function(a,b){var c,d=D(b,1),e=D(b,2),f;if(f=c=b.getLocation())f={latitude:D(c,1),longitude:D(c,2)},a&&(f.V=c);c={Z:d,$:e,location:f};a&&(c.V=b);return c});tc.prototype.getLocation=function(){return F(this,uc,3)};var uc=function(a){C(this,a,-1,null)};w(uc,B);
var wc=function(a,b){ua(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:vc.hasOwnProperty(d)?a.setAttribute(vc[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})},vc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"},yc=function(a,b,c){var d=arguments,
e=document,f=d[1],g=e.createElement(d[0]);f&&(q(f)?g.className=f:n(f)?g.className=f.join(" "):wc(g,f));2<d.length&&xc(e,g,d);return g},xc=function(a,b,c){function d(c){c&&b.appendChild(q(c)?a.createTextNode(c):c)}for(var e=2;e<c.length;e++){var f=c[e];!ca(f)||da(f)&&0<f.nodeType?d(f):oa(zc(f)?ra(f):f,d)}},zc=function(a){if(a&&"number"==typeof a.length){if(da(a))return"function"==typeof a.item||"string"==typeof a.item;if("function"==ba(a))return"function"==typeof a.item}return!1};
var T=function(a){mc.call(this,a||new La);this.c=Ac(this);this.i=S(this);this.s=Bc(this);a=this.a;a.a||(a.a={});if(!a.a[3]){for(var b=D(a,3),c=[],d=0;d<b.length;d++)c[d]=new Ma(b[d]);a.a[3]=c}b=a.a[3];b==za&&(b=a.a[3]=[]);a=b;for(b=0;b<a.length;b++)c=new Na(a[b]),F(c.a,J,1).B();a=F(this.a,Ja,10);!this.o&&a&&(this.o=new sc(a));this.o=this.o||null;a=F(this.a,Ia,13);!this.D&&a&&(this.D=new rc(a));this.D=this.D||null;new vb;this.B()||(Jb.M(),a=Lb(0),this.a.F()||(b=new J,G(this.a,1,b)),b=this.a.F(),E(b,
1,a))};w(T,mc);Ib("gws.collections.models.ClipModel");T.prototype.clone=function(){var a;a=this.a;a=new a.constructor(Ba(a.c));return new T(a)};var Ac=function(a){var b=F(a.a,Fa,5);!a.c&&b&&(a.c=new qc(b));if(!a.c&&3==D(a.a,4)){var b=Bc(a),b=z(D(b.a,1)).replace(/\//g,"-"),b="https://www.gstatic.com/vd/kp/%s/en/1/image.jpg".replace("%s",b),c=yc("img");c.src=b;c.onload=u(a.O,a,c)}return a.c||null};
T.prototype.O=function(a){var b=new qc,c=a.src,d=F(b.a,H,3);E(d,1,c);new M(pc(b));c=a.naturalWidth;a=a.naturalHeight;d=F(b.a,H,3);E(d,2,c);c=F(b.a,H,3);E(c,3,a);var c=(a=new Mb(3))||new Mb,d=this.c&&this.c.l(),e=b.l();d!=e&&(this.c=b,G(this.a,5,b.a),b=v(),E(this.a,8,b),b=na(this,203,d||"",e,c),Ob(c,b,this),c!=a&&0<c.c.length&&Nb(this,c))};var Bc=function(a){var b=F(a.a,Da,9);!a.s&&b&&(a.s=new Ea(b));return a.s||null},S=function(a){var b=F(a.a,Ha,6);!a.i&&b&&(a.i=new rb(b));return a.i||null};
T.prototype.getTitle=function(){return S(this)?S(this).getTitle().toString():""};T.prototype.setTitle=function(a,b){var c=b||new Mb;if(S(this).getTitle()==a)return!1;var d=S(this).l(),e=S(this);e.setTitle(a);var f=v();E(this.a,8,f);d=na(this,204,d,e.l(),c);Ob(c,d,this);c!=b&&0<c.c.length&&Nb(this,c);return!0};var Cc=function(a,b){var c=new Mb,d=D(a.a,4);D(a.a,4)!=b&&(E(a.a,4,b),d=na(a,206,""+d,""+b,c),Ob(c,d,a),void 0!=c&&0<c.c.length&&Nb(a,c))}; T.prototype.toString=function(){return"ClipModel:"+this.B()};T.prototype.getLocation=function(){var a=this.a.X();return a&&(a=a.getLocation())?z(D(a,1).toFixed(4)+","+D(a,2).toFixed(4)):""};
var Dc=function(a){x.call(this);this.i=a;this.a={};this.c={}};w(Dc,x);Dc.prototype.C=function(){this.unlisten();Dc.H.C.call(this)};Dc.prototype.listen=function(a,b){var c=u(b,this.i);a.addListener(c);var d=a[r]||(a[r]=++ea);d in this.a?this.c[d].a.set(ub(c),c):(this.a[d]=a,this.c[d]=new vb([c]));return this};Dc.prototype.unlisten=function(a){if(a){var b=a[r]||(a[r]=++ea);if(b in this.a){var c=this.c[b].v();oa(c,a.removeListener,a);delete this.c[b];delete this.a[b]}}else ua(this.a,this.unlisten,this)};
var Ec=function(){R.call(this);this.O=new nc(this);ia(this,ha(ja,this.O))};w(Ec,R);Ec.prototype.c=function(a){this.m=a};var Fc=function(a,b){this.width=a;this.height=b},Gc=function(a){return a.width*a.height};var U=function(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.w=function(a,c,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[c].apply(a,g)}},Hc={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},Ic={IMG:" ",BR:"\n"},Jc=/&([^;\s<&]+);?/g,V=function(a,b){var c=Kc(a);return c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,null))?c[b]||c.getPropertyValue(b)||"":""},Mc=function(a){if("none"!=
V(a,"display"))return Lc(a);var b=a.style,c=b.display,d=b.visibility,e=b.position;b.visibility="hidden";b.position="absolute";b.display="inline";a=Lc(a);b.display=c;b.position=e;b.visibility=d;return a},Lc=function(a){var b=a.offsetWidth,c=a.offsetHeight;return void 0===b||!b&&!c?(a=a.getBoundingClientRect(),new Fc(a.right-a.left,a.bottom-a.top)):new Fc(b,c)},Kc=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document},Nc=function(a){if(a.parentElement)return a.parentElement;a=a.parentNode;
return"object"==typeof a&&1==a.nodeType?a:null},Pc=function(a){var b=[];Oc(a,b);a=b.join("");a=a.replace(/ +/g," ");" "!=a&&(a=a.replace(/^\s*/,""));return a},Oc=function(a,b){if(!(a.nodeName in Hc))if(3==a.nodeType)b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,""));else if(a.nodeName in Ic)b.push(Ic[a.nodeName]);else for(var c=a.firstChild;c;)Oc(c,b),c=c.nextSibling},Qc=function(a){if(-1==a.indexOf("&"))return a;var b={"&amp;":"&","&lt;":"<","&gt;":">","&quot;":'"'},c;c=document.createElement("div");
return a.replace(Jc,function(a,e){var f=b[a];if(f)return f;if("#"==e.charAt(0)){var g=Number("0"+e.substr(1));isNaN(g)||(f=String.fromCharCode(g))}f||(c.innerHTML=a+" ",f=c.firstChild.nodeValue.slice(0,-1));return b[a]=f})},Rc=function(a){return a&&5<=a.length?"d"==a.charAt(0)&&"a"==a.charAt(1)&&"t"==a.charAt(2)&&"a"==a.charAt(3)&&":"==a.charAt(4):!1};
var Sc=function(){this.a=["ad","advertisement","ads","sponsor","sponsored"]};Sc.prototype.filter=function(a){for(;a;){for(var b=a.classList,c=0;c<b.length;++c)for(var d=b[c].split(/\W+/),e=0;e<d.length;++e)if(0<=this.a.indexOf(d[e].toLowerCase()))return!1;a=Nc(a)}return!0};
var Tc=function(a){this.c=a},Uc=function(a,b){return a==b?0:a.c-b.c};var W=function(){this.h=[]};W.prototype.filter=function(a){for(var b=0;b<this.h.length;++b)if(!this.h[b].filter(a))return!1;return!0};var Vc=function(a,b){var c=a.a(b);if(0==c.length)return null;for(var d=c[0],e=1;e<c.length;++e){var f=c[e];f.c>d.c&&(d=f)}return d};W.prototype.a=function(a){return X(this,a.getElementsByTagName("*"))};var X=function(a,b,c){for(var d=[],e=b.length,f=0;f<e;++f){var g=a.c(b[f],c);g&&d.push(g)}return d};W.prototype.c=function(){return null};
var Y=function(a,b,c,d){Y.w(this,"constructor",a);this.a=b;this.g=c;this.h=d};U(Y,Tc);var Wc=function(){};Wc.prototype.filter=function(a){for(;a;){if("none"==V(a,"display"))return!1;var b=Mc(a);if("hidden"==V(a,"overflow")&&0==Gc(b)||"hidden"==V(a,"visibility"))return!1;a=Nc(a)}return!0};var Xc=function(){Xc.w(this,"constructor");this.h.push(new Sc);this.h.push(new Wc);this.g=document.createElement("a")};U(Xc,W);var Yc={".gif":.5},Zc=function(){this.T=0;this.N={}};Xc.prototype.a=function(a){return X(this,a.getElementsByTagName("*"),new Zc)};
Xc.prototype.c=function(a,b){var c=null;switch(a.tagName.toLowerCase()){case "meta":c=$c(this,a,1,"property","og:image","content")||$c(this,a,.9,"name","msapplication-tileimage","content")||$c(this,a,.8,"name","twitter:image","content")||ad(a);break;case "link":c=$c(this,a,.7,"rel","apple-touch-icon","href")||$c(this,a,.6,"rel","image_src","href")||ad(a);break;case "img":if(this.filter(a))a:{if((c=a.src)&&!Rc(c)){var d=new Fc(a.naturalWidth,a.naturalHeight),e=Mc(a),f=Gc(d)<Gc(e)?d:e;if(f.width&&f.height){f=
bd(a);c=new Y(f,c,d,e);break a}}c=null}break;default:if(this.filter(a)&&30>b.T){a:{c=V(a,"background-image");d=V(a,"background-repeat");e=V(a,"background-size");if(c&&("no-repeat"==d||"cover"==e)&&c&&5<=c.length&&"u"==c.charAt(0)&&"r"==c.charAt(1)&&"l"==c.charAt(2)&&"("==c.charAt(3)&&")"==c.charAt(c.length-1)&&(c=c.substr(4,c.length-5))&&!Rc(c)&&(d=Mc(a),d.width&&d.height)){for(var e=bd(a),f=a.children,g=0;g<f.length;++g){var h=f[g];if("none"!=V(h,"display")&&Gc(Mc(h))>.1*Gc(d)){e*=.1;break}}c=new Y(e,
c,void 0,d);break a}c=null}c&&++b.T}}if(!c)return null;e=c.h||c.g;if(c.a!=document.location.href&&(100>e.width||100>e.height))return null;d=c.c;d/=1+Math.exp(-1E-5*Gc(e));e=e.width/e.height;1>e&&(e=1/e);2<e&&(d*=.8);e=c.a;this.g.href=e;e=this.g.href;f=decodeURIComponent(this.g.pathname||"");g=f.lastIndexOf(".");0<g&&(f=Yc[f.slice(g)])&&(d*=f);if(e in b.N&&b.N[e]>d)return null;b.N[e]=d;return new Y(d,e,c.g,c.h)};
var $c=function(a,b,c,d,e,f){if(b.hasAttribute(d)&&b.getAttribute(d).toLowerCase()==e.toLowerCase()){d=b.getAttribute(f);if(!d||Rc(d))return null;e=parseInt(b.getAttribute("data-google-stars-image-width"),10);f=parseInt(b.getAttribute("data-google-stars-image-height"),10);if(e&&f)return b=Kc(b),a.g.href=b.documentURI,"/"!=a.g.pathname&&-1==b.body.innerHTML.indexOf(d)&&(c*=.5),new Y(c,d,new Fc(e,f))}return null},ad=function(a){var b=a.getAttribute("itemprop");if(b&&"thumbnailurl"==b.toLowerCase()){b=
a.getAttribute("href")||a.getAttribute("content");if(!b||Rc(b))return null;var c=parseInt(a.getAttribute("data-google-stars-image-width"),10);a=parseInt(a.getAttribute("data-google-stars-image-height"),10);if(c&&a)return new Y(.55,b,new Fc(c,a))}return null},bd=function(a){var b=Kc(a);if(a==b.documentElement)a=0;else{var c=b.body||b.documentElement,b=b.defaultView.pageYOffset||c.scrollTop;a=a.getBoundingClientRect().top+b}return 2E3<a?0:1/(1+Math.exp(.001*a))};
var cd=function(a,b){cd.w(this,"constructor",a);this.a=b};U(cd,Tc);var dd=function(){dd.w(this,"constructor")};U(dd,W);dd.prototype.a=function(a){var b=X(this,a.getElementsByTagName("meta"));b.push(ed(a));if(a=a.defaultView)a=a.getSelection().toString(),0<a.length&&b.push(new cd(1,a));return b};
dd.prototype.c=function(a){var b=0,c="";switch(a.tagName.toLowerCase()){case "meta":var d=a.getAttribute("name"),e=a.getAttribute("property");if(e&&"og:description"==e.toLowerCase())b=.9;else if(d)switch(d.toLowerCase()){case "twitter:description":b=.8;break;case "description":b=.7;break;case "msapplication-tooltip":b=.6}0<b&&(c=a.getAttribute("content")||"")}do a=c,c=Qc(c);while(c!=a);c=c.replace(/<[^<>]*?>/g,"");c=c.trim();return 5<c.length?(1024<c.length&&(c=c.substr(0,1021)+"..."),new cd(b,c)):
null};
var ed=function(a){if(a.body){var b="",c="",d=0;a=a.body.innerText.replace(/(\r\n|\r)/g,"\n");for(var e=a.split("\n"),f=0;f<e.length;++f){for(var b=e[f].trim().replace(/\s+/g," "),g=b.split(" "),h=g.length,k,t=k=0;t<b.length;++t){var p=b.charAt(t);("a"<=p&&"z">=p||"A"<=p&&"Z">=p)&&++k}if(t=64<=b.length&&8<=h&&k>=.4*b.length){for(p=t=0;p<b.length;++p)/[^a-zA-Z0-9\r\n\t ]/.test(b.charAt(p))&&++t;t=0<t}if(t&&24>=fd(g))break;k>=.4*b.length&&h>d&&24>=fd(g)&&(c=b,d=h);b=""}0==b.length&&20<c.length&&4<= d&&(b=c);a=a.trim().replace(/[\t\n ]+/g," ");return new cd(.1,b||a.substring(0,1024))}return null},fd=function(a){for(var b=0,c=0;c<a.length;++c)b=Math.max(a[c].length,b);return b};
var gd=function(a,b){gd.w(this,"constructor",a);this.a=b};U(gd,Tc);var hd=function(a){return a.a};var id=function(a,b,c){id.w(this,"constructor",a);this.g=b;this.a=c};U(id,Tc);var jd=function(a,b,c,d){this.g=a;this.a=b;this.c=c;this.h=d};jd.prototype.getTitle=function(){return this.g};var kd=function(){kd.w(this,"constructor")};U(kd,W);kd.prototype.a=function(a){var b=X(this,a.getElementsByTagName("meta")).concat(X(this,a.getElementsByTagName("title"))),c=X(this,a.getElementsByTagName("h1"));0<c.length?1==c.length&&(b=b.concat(c)):(c=X(this,a.getElementsByTagName("h2")),0<c.length?1==c.length&&(b=b.concat(c)):(c=X(this,a.getElementsByTagName("h3")),0<c.length&&1==c.length&&(b=b.concat(c))));a.title&&b.push(new gd(1,a.title));b.push(new gd(.1,a.documentURI));return b};
kd.prototype.c=function(a){var b=0,c="";switch(a.tagName.toLowerCase()){case "title":b=.5;c=Pc(a);break;case "h1":b=.4;c=Pc(a);break;case "h2":b=.3;c=Pc(a);break;case "h3":b=.2;c=Pc(a);break;case "meta":var d=a.getAttribute("name"),e=a.getAttribute("property");if(e&&"og:title"==e.toLowerCase())b=.9;else if(d)switch(d.toLowerCase()){case "application-name":b=.8;break;case "twitter:title":b=.7;break;case "title":b=.6}0<b&&(c=a.getAttribute("content")||"")}c=c.trim();do a=c,c=Qc(c);while(a!=c);return 1< c.length?new gd(b,c):null};
var ld=function(){ld.w(this,"constructor")};U(ld,W);ld.prototype.c=function(a){switch(a.tagName.toLowerCase()){case "meta":var b;a:{if(a.hasAttribute("property")&&"og:video"==a.getAttribute("property").toLowerCase()){b=a.getAttribute("content");var c=parseInt(a.getAttribute("data-google-stars-video-width"),10);a=parseInt(a.getAttribute("data-google-stars-video-height"),10);if(b&&0<c&&0<a){b=new id(1,b,new Fc(c,a));break a}}b=null}return b}return null};
var md=function(){this.g=new kd;this.c=new dd;this.a=new Xc;this.h=new ld};var nd=function(){this.a=0;this.g=Promise.resolve();this.c=null},qd=function(a){if(0==a.a){var b=document.getElementsByTagName("meta"),c=document.getElementsByTagName("link");a.a=b.length+c.length;if(0<a.a){a.g=new Promise(function(a){this.c=a}.bind(a));for(var d=0;d<b.length;d++)od(a,b[d]);for(d=0;d<c.length;d++)pd(a,c[d]);setTimeout(a.c,5E3)}else a.g=Promise.resolve()}return a.g},od=function(a,b){var c="";if(b.hasAttribute("property"))switch(b.getAttribute("property").toLowerCase()){case "og:image":var c=
b.getAttribute("content"),d=Nc(b).children,e=rd(d,"og:image:width"),d=rd(d,"og:image:height");0<e&&0<d&&(b.setAttribute("data-google-stars-image-width",e),b.setAttribute("data-google-stars-image-height",d));break;case "og:video":d=Nc(b).children,e=rd(d,"og:video:width"),d=rd(d,"og:video:height"),0<e&&0<d&&(b.setAttribute("data-google-stars-video-width",e),b.setAttribute("data-google-stars-video-height",d))}else if(b.hasAttribute("name"))switch(b.getAttribute("name").toLowerCase()){case "msapplication-tileimage":case "twitter:image":c=
b.getAttribute("content")}else if(b.hasAttribute("itemprop"))switch(b.getAttribute("itemprop").toLowerCase()){case "thumbnailurl":c=b.getAttribute("href")||b.getAttribute("content")}sd(a,c,b)},pd=function(a,b){var c="";if(b.hasAttribute("rel"))switch(b.getAttribute("rel").toLowerCase()){case "apple-touch-icon-precomposed":case "apple-touch-icon":case "image_src":c=b.getAttribute("href")}else if(b.hasAttribute("itemprop"))switch(b.getAttribute("itemprop").toLowerCase()){case "thumbnailurl":c=b.getAttribute("href")||
b.getAttribute("content")}sd(a,c,b)},rd=function(a,b){for(var c=0;c<a.length;++c){var d=a[c];if(d.hasAttribute("property")&&d.getAttribute("property").toLowerCase()==b&&d.hasAttribute("content"))return d.getAttribute("content")}return""},sd=function(a,b,c){!b||c.hasAttribute("data-google-stars-image-width")&&c.hasAttribute("data-google-stars-image-height")?0==--a.a&&a.c():td(a,b,a.h.bind(a,c))},td=function(a,b,c){var d=new Image,e=function(b){"load"==b.type&&c(d.naturalWidth,d.naturalHeight);0==--a.a&&
a.c();d.removeEventListener("load",e);d.removeEventListener("error",e)};d.addEventListener("load",e);d.addEventListener("error",e);d.src=b};nd.prototype.h=function(a,b,c){a.setAttribute("data-google-stars-image-width",b);a.setAttribute("data-google-stars-image-height",c)};
var ud=function(){Ec.call(this);this.a=null;this.s=new nd;this.i=null;this.o=new Dc(this);ia(this,ha(ja,this.o))};w(ud,Ec);var vd=Ib("image.collections.extension.ContentController");ud.prototype.c=function(a){ud.H.c.call(this,a);this.o.listen(chrome.runtime.onMessage,this.W)};
ud.prototype.W=function(a,b,c){c({received:"true"});switch(a.type){case "collect_page":if(null===this.a){b=a.clipId;c=a.userId;a=new J;E(a,1,b);E(a,2,c);b=new La;G(b,1,a);a=v();E(b,7,a);E(b,8,a);this.a=new T(b);b=document.documentURI;/\.(jpg|jpeg|png|gif|bmp|svg|tiff)$/i.test(b)?Cc(this.a,1):Cc(this.a,2);a=new rb;try{ob(b)}catch(d){b=encodeURI(b)}try{ob(b)}catch(e){b=""}E(a.a,3,b);b=this.a;b.i=a;G(b.a,6,a.a);qd(this.s).then(u(this.D,this,!0))}else vd&&vd.log(Bb,"Clip is already being created",void 0);
break;case "get_salient_images":qd(this.s).then(u(this.D,this,!1));break;default:vd&&vd.log(Ab,"Invalid message type: "+a.type,void 0)}};
ud.prototype.D=function(a){this.i||(this.i=new md);var b,c=this.i,d=document,e=Vc(c.g,d);b=Vc(c.c,d);for(var f=c.a.a(d),c=Vc(c.h,d),d=0,g={},h=0;h<f.length;h++)g[f[h].a]||(g[f[h].a]=!0,f[d++]=f[h]);f.length=d;b=new jd(e,b,f,c);f=b.c;f.sort(Uc||sa);e=[];d=null;for(c=0;c<f.length;c++){g=d=new qc;h=f[c].a;g.c=null;try{var k=I(g.a);E(k,1,h);g.c=new M(z(Ga(I(g.a))))}catch(t){h=I(g.a),E(h,1,void 0),h=I(g.a),E(h,2,void 0),h=I(g.a),E(h,3,void 0)}g.c&&D(g.a,6)&&E(g.a,6,!1);var p=f[c].g;if(p){var g=d,h=p.width,
p=p.height,Fd=I(g.a);E(Fd,2,h);g=I(g.a);E(g,3,p)}e.unshift(d.l())}if(a){!Ac(this.a)&&d&&(a=this.a,k=d,a.c=k,G(a.a,5,k.a),k=v(),E(a.a,8,k));a=S(this.a);!a.getTitle()&&b.getTitle()&&a.setTitle(hd(b.getTitle()));!z(D(a.a,2))&&b.a&&E(a.a,2,b.a.a);if(k=b.h)Cc(this.a,4),a=new sc,E(a.a,1,k.g),b=k.a.height,E(a.a,2,k.a.width),E(a.a,3,b),k=this.a,k.o=a,G(k.a,10,a.a);chrome.runtime.sendMessage({type:"created_clip",clipData:this.a.l(),images:e});this.a=null}else chrome.runtime.sendMessage({type:"salient_images_found", images:e})};
var wd=function(){this.a=v()},xd=new wd;wd.prototype.set=function(a){this.a=a};wd.prototype.get=function(){return this.a};var yd=function(a){this.h=a||"";this.i=xd};yd.prototype.a=!0;yd.prototype.c=!0;yd.prototype.g=!1;var Z=function(a){return 10>a?"0"+a:String(a)},zd=function(a,b){var c=(a.g-b)/1E3,d=c.toFixed(3),e=0;if(1>c)e=2;else for(;100>c;)e++,c*=10;for(;0<e--;)d=" "+d;return d},Ad=function(a){yd.call(this,a)};w(Ad,yd);
var Bd=function(){u(this.h,this);this.a=new Ad;this.a.c=!1;this.a.g=!1;this.c=this.a.a=!1;this.g="";this.i={}};
Bd.prototype.h=function(a){if(!this.i[a.c]){var b;b=this.a;var c=[];c.push(b.h," ");if(b.c){var d=new Date(a.g);c.push("[",Z(d.getFullYear()-2E3)+Z(d.getMonth()+1)+Z(d.getDate())+" "+Z(d.getHours())+":"+Z(d.getMinutes())+":"+Z(d.getSeconds())+"."+Z(Math.floor(d.getMilliseconds()/10)),"] ")}c.push("[",zd(a,b.i.get()),"s] ");c.push("[",a.c,"] ");c.push(a.getMessage());b.g&&(d=a.a)&&c.push("\n",d instanceof Error?d.message:d.toString());b.a&&c.push("\n");b=c.join("");if(c=Cd)switch(a.h){case zb:Dd(c, "info",b);break;case Ab:Dd(c,"error",b);break;case Bb:Dd(c,"warn",b);break;default:Dd(c,"debug",b)}else this.g+=b}};var Cd=m.console,Dd=function(a,b,c){if(a[b])a[b](c);else a.log(c)};
var Ed=function(){R.call(this);this.a=new ud;ia(this,ha(ja,this.a))};w(Ed,R);aa(Ed);var Gd=new Bd;0!=Gd.c&&(Hb(),Gd.c=!1);var Hd=Ib("image.collections.extension.Content"),Id=Ed.M();Hd&&Hd.log(Cb,"Initializing extension content",void 0);Id.a.c(Id);window.full_script_injected=!0;

}catch(e){_DumpException(e)}
// Google Inc.
