try{
'use strict';var f=this,aa=function(){},g=function(a){a.l=function(){return a.s?a.s:a.s=new a}},ba=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=
typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},l=function(a){return"function"==ba(a)},ca=function(a,b,c){return a.call.apply(a.bind,arguments)},da=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);
return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},m=function(a,b,c){m=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ca:da;return m.apply(null,arguments)},ea=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}},fa=Date.now||function(){return+new Date};
var n;a:{var p=f.navigator;if(p){var q=p.userAgent;if(q){n=q;break a}}n=""};var r=function(a){a()},ga=function(a){var b=document.body;b&&a&&r(function(){b.appendChild(a)})},ha=function(a,b){r(function(){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=b;else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=b}else{for(var c;c=a.firstChild;)a.removeChild(c);a.appendChild((9==a.nodeType?a:a.ownerDocument||a.document).createTextNode(String(b)))}})};
var t=function(a,b,c){this.h=c;this.g=a;this.i=b;this.c=0;this.a=null};t.prototype.get=function(){var a;0<this.c?(this.c--,a=this.a,this.a=a.next,a.next=null):a=this.g();return a};var u=function(a,b){a.i(b);a.c<a.h&&(a.c++,b.next=a.a,a.a=b)};var v=function(a){f.setTimeout(function(){throw a;},0)},w,ia=function(){var a=f.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&-1==n.indexOf("Presto")&&(a=function(){var a=document.createElement("IFRAME");a.style.display="none";a.src="";document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+
b.location.host,a=m(function(a){if(("*"==d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&-1==n.indexOf("Edge")&&-1==n.indexOf("Trident")&&-1==n.indexOf("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(void 0!==c.next){c=c.next;var a=c.o;c.o=null;a()}};return function(a){d.next={o:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof document&&
"onreadystatechange"in document.createElement("SCRIPT")?function(a){var b=document.createElement("SCRIPT");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};document.documentElement.appendChild(b)}:function(a){f.setTimeout(a,0)}};
var y=function(){this.c=this.a=null},A=new t(function(){return new z},function(a){a.reset()},100);y.prototype.add=function(a,b){var c=A.get();c.set(a,b);this.c?this.c.next=c:this.a=c;this.c=c};y.prototype.remove=function(){var a=null;this.a&&(a=this.a,this.a=this.a.next,this.a||(this.c=null),a.next=null);return a};var z=function(){this.next=this.c=this.a=null};z.prototype.set=function(a,b){this.a=a;this.c=b;this.next=null};z.prototype.reset=function(){this.next=this.c=this.a=null};
var F=function(a,b){C||ja();D||(C(),D=!0);E.add(a,b)},C,ja=function(){if(f.Promise&&f.Promise.resolve){var a=f.Promise.resolve();C=function(){a.then(G)}}else C=function(){var a=G;!l(f.setImmediate)||f.Window&&f.Window.prototype&&f.Window.prototype.setImmediate==f.setImmediate?(w||(w=ia()),w(a)):f.setImmediate(a)}},D=!1,E=new y,G=function(){for(var a=null;a=E.remove();){try{a.a.call(a.c)}catch(b){v(b)}u(A,a)}D=!1};
var I=function(a,b){this.a=0;this.v=void 0;this.g=this.c=this.h=null;this.i=this.m=!1;if(a==ka)H(this,2,b);else try{var c=this;a.call(b,function(a){H(c,2,a)},function(a){H(c,3,a)})}catch(d){H(this,3,d)}},J=function(){this.next=this.g=this.c=this.h=this.a=null;this.i=!1};J.prototype.reset=function(){this.g=this.c=this.h=this.a=null;this.i=!1};
var K=new t(function(){return new J},function(a){a.reset()},100),L=function(a,b,c){var d=K.get();d.h=a;d.c=b;d.g=c;return d},ka=function(){},la=function(a){return new I(function(b,c){var d=a.length,e=[];if(d)for(var k=function(a,c){d--;e[a]=c;0==d&&b(e)},h=function(a){c(a)},x=0,N;N=a[x];x++)M(N,ea(k,x),h);else b(e)})};I.prototype.then=function(a,b,c){return ma(this,l(a)?a:null,l(b)?b:null,c)};I.prototype.then=I.prototype.then;I.prototype.$goog_Thenable=!0;
var M=function(a,b,c,d){a instanceof I?O(a,L(b||aa,c||null,d)):a.then(b,c,d)},O=function(a,b){a.c||2!=a.a&&3!=a.a||P(a);a.g?a.g.next=b:a.c=b;a.g=b},ma=function(a,b,c,d){var e=L(null,null,null);e.a=new I(function(a,h){e.h=b?function(c){try{var e=b.call(d,c);a(e)}catch(B){h(B)}}:a;e.c=c?function(b){try{var e=c.call(d,b);a(e)}catch(B){h(B)}}:h});e.a.h=a;O(a,e);return e.a};I.prototype.w=function(a){this.a=0;H(this,2,a)};I.prototype.A=function(a){this.a=0;H(this,3,a)};
var H=function(a,b,c){if(0==a.a){if(a==c)b=3,c=new TypeError("Promise cannot resolve to itself");else{var d;if(c)try{d=!!c.$goog_Thenable}catch(e){d=!1}else d=!1;if(d){a.a=1;M(c,a.w,a.A,a);return}d=typeof c;if("object"==d&&null!=c||"function"==d)try{var k=c.then;if(l(k)){na(a,c,k);return}}catch(h){b=3,c=h}}a.v=c;a.a=b;a.h=null;P(a);3!=b||oa(a,c)}},na=function(a,b,c){a.a=1;var d=!1,e=function(b){d||(d=!0,a.w(b))},k=function(b){d||(d=!0,a.A(b))};try{c.call(b,e,k)}catch(h){k(h)}},P=function(a){a.m||
(a.m=!0,F(a.B,a))},pa=function(a){var b=null;a.c&&(b=a.c,a.c=b.next,b.next=null);a.c||(a.g=null);return b};I.prototype.B=function(){for(var a=null;a=pa(this);){var b=this.a,c=this.v;if(3==b&&a.c&&!a.i)for(var d=void 0,d=this;d&&d.i;d=d.h)d.i=!1;if(a.a)a.a.h=null,Q(a,b,c);else try{a.i?a.h.call(a.g):Q(a,b,c)}catch(e){R.call(null,e)}u(K,a)}this.m=!1};var Q=function(a,b,c){2==b?a.h.call(a.g,c):a.c&&a.c.call(a.g,c)},oa=function(a,b){a.i=!0;F(function(){a.i&&R.call(null,b)})},R=v;
var S=function(){this.c={};this.a={}};g(S);var T=function(a,b,c,d,e){this.reset(a,b,c,d,e)};T.prototype.a=null;var qa=0;T.prototype.reset=function(a,b,c,d,e){"number"==typeof e||qa++;d||fa();this.c=b;delete this.a};T.prototype.getMessage=function(){return this.c};var U=function(a){this.h=a;this.c=this.g=this.a=null},V=function(a,b){this.name=a;this.value=b};V.prototype.toString=function(){return this.name};var ra=new V("SEVERE",1E3),sa=new V("CONFIG",700);U.prototype.getChildren=function(){this.c||(this.c={});return this.c};var W=function(a){return a.g?a.g:a.a?W(a.a):null};
U.prototype.log=function(a,b,c){if(a.value>=W(this).value)for(l(b)&&(b=b()),a=new T(a,String(b),this.h),c&&(a.a=c),c="log:"+a.getMessage(),f.console&&(f.console.timeStamp?f.console.timeStamp(c):f.console.markTimeline&&f.console.markTimeline(c)),f.msWriteProfilerMark&&f.msWriteProfilerMark(c),c=this;c;)c=c.a};var X={},Y=null,ta=function(a){Y||(Y=new U(""),X[""]=Y,Y.g=sa);var b;if(!(b=X[a])){b=new U(a);var c=a.lastIndexOf("."),d=a.substr(c+1),c=ta(a.substr(0,c));c.getChildren()[d]=b;b.a=c;X[a]=b}return b};
var Z;Z=ta("image.collections.extension.Promises");var R=function(a){Z&&Z.log(ra,a.toString(),void 0)},ua=function(a,b,c){return function(d){var e=chrome.runtime.lastError;e?(d=S.l(),a&&(d.a[a]=(d.a[a]||0)+1),c(e.message||"Unknown Chrome API error")):(e=S.l(),a&&(e.c[a]=(e.c[a]||0)+1),b(d))}},va=function(a,b){return new I(function(c,d){chrome.tabs.sendMessage(a,b,ua("chrome.tabs.sendMessage",c,d))})},wa=function(){return new I(function(a,b){chrome.tabs.getCurrent(ua("chrome.tabs.getCurrent",a,b))})};
var xa=function(){};g(xa);(function(){xa.l();var a={type:"get_log_history"},b={type:"get_chrome_api_logs"};wa().then(function(c){c=c.openerTabId;return la([va(c,a),va(c,b)])}).then(function(a){var b;b=document.createElement("pre");ha(b,a[0]+"\nChrome API calls:\n"+a[1]);ga(b)})})();

}catch(e){_DumpException(e)}
// Google Inc.
