try{
'use strict';var h=this,k=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b},aa=function(a,b,c){return a.call.apply(a.bind,arguments)},ba=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},l=function(a,b,c){l=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?
aa:ba;return l.apply(null,arguments)},ca=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}},m=Date.now||function(){return+new Date},n=function(a,b){function c(){}c.prototype=b.prototype;a.o=b.prototype;a.prototype=new c;a.H=function(a,c,f){for(var g=Array(arguments.length-2),t=2;t<arguments.length;t++)g[t-2]=arguments[t];return b.prototype[c].apply(a,g)}};
var da=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},p=function(a,b){return a<b?-1:a>b?1:0};var q=Array.prototype;var r;a:{var ea=h.navigator;if(ea){var fa=ea.userAgent;if(fa){r=fa;break a}}r=""};var ga=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};var ha=function(){this.c="";this.a=null},ia=function(a){var b=new ha;b.c=a;b.a=0};ia("<!DOCTYPE html>");ia("");var ja="",u=/WebKit\/(\S+)/.exec(r);u&&(ja=u?u[1]:"");
var ka=ja,la={},ma=function(){if(!la["528"]){for(var a=0,b=da(String(ka)).split("."),c=da("528").split("."),d=Math.max(b.length,c.length),e=0;0==a&&e<d;e++){var f=b[e]||"",g=c[e]||"",t=/(\d*)(\D*)/g,Da=/(\d*)(\D*)/g;do{var x=t.exec(f)||["","",""],y=Da.exec(g)||["","",""];if(0==x[0].length&&0==y[0].length)break;a=p(0==x[1].length?0:parseInt(x[1],10),0==y[1].length?0:parseInt(y[1],10))||p(0==x[2].length,0==y[2].length)||p(x[2],y[2])}while(0==a)}la["528"]=0<=a}};
var v=function(a,b,c,d,e){this.reset(a,b,c,d,e)};v.prototype.a=null;var na=0;v.prototype.reset=function(a,b,c,d,e){"number"==typeof e||na++;this.g=d||m();this.h=a;this.i=b;this.c=c;delete this.a};v.prototype.getMessage=function(){return this.i};var w=function(a){this.h=a;this.c=this.g=this.a=null},z=function(a,b){this.name=a;this.value=b};z.prototype.toString=function(){return this.name};var oa=new z("SHOUT",1200),pa=new z("SEVERE",1E3),qa=new z("WARNING",900),ra=new z("INFO",800),sa=new z("CONFIG",700);w.prototype.getChildren=function(){this.c||(this.c={});return this.c};var ta=function(a){return a.g?a.g:a.a?ta(a.a):null};
w.prototype.log=function(a,b,c){if(a.value>=ta(this).value)for("function"==k(b)&&(b=b()),a=new v(a,String(b),this.h),c&&(a.a=c),c="log:"+a.getMessage(),h.console&&(h.console.timeStamp?h.console.timeStamp(c):h.console.markTimeline&&h.console.markTimeline(c)),h.msWriteProfilerMark&&h.msWriteProfilerMark(c),c=this;c;)c=c.a}; var A={},B=null,ua=function(){B||(B=new w(""),A[""]=B,B.g=sa)},C=function(a){ua();var b;if(!(b=A[a])){b=new w(a);var c=a.lastIndexOf("."),d=a.substr(c+1),c=C(a.substr(0,c));c.getChildren()[d]=b;b.a=c;A[a]=b}return b};
C("image.collections.extension.Promises");var D=function(a){this.a=a},va={"stars-gws":"https://www.google.com","stars-last-import-time":0};D.prototype.get=function(a,b){this.a.get(a,l(this.c,this,a,b))};D.prototype.c=function(a,b,c){null!=c||(c={});for(var d=0;d<a.length;++d){var e=a[d];e in c||(c[e]=va[e])}b(c)};D.prototype.set=function(a){this.a.set(a)};
var E=function(){this.a=m()},wa=new E;E.prototype.set=function(a){this.a=a};E.prototype.reset=function(){this.set(m())};E.prototype.get=function(){return this.a};var F=function(a){this.h=a||"";this.i=wa};F.prototype.a=!0;F.prototype.c=!0;F.prototype.g=!1;var G=function(a){return 10>a?"0"+a:String(a)},xa=function(a,b){var c=(a.g-b)/1E3,d=c.toFixed(3),e=0;if(1>c)e=2;else for(;100>c;)e++,c*=10;for(;0<e--;)d=" "+d;return d},ya=function(a){F.call(this,a)};n(ya,F);
var za=function(){l(this.h,this);this.a=new ya;this.a.c=!1;this.a.g=!1;this.c=this.a.a=!1;this.g="";this.i={}};
za.prototype.h=function(a){if(!this.i[a.c]){var b;b=this.a;var c=[];c.push(b.h," ");if(b.c){var d=new Date(a.g);c.push("[",G(d.getFullYear()-2E3)+G(d.getMonth()+1)+G(d.getDate())+" "+G(d.getHours())+":"+G(d.getMinutes())+":"+G(d.getSeconds())+"."+G(Math.floor(d.getMilliseconds()/10)),"] ")}c.push("[",xa(a,b.i.get()),"s] ");c.push("[",a.c,"] ");c.push(a.getMessage());b.g&&(d=a.a)&&c.push("\n",d instanceof Error?d.message:d.toString());b.a&&c.push("\n");b=c.join("");if(c=Aa)switch(a.h){case oa:H(c, "info",b);break;case pa:H(c,"error",b);break;case qa:H(c,"warn",b);break;default:H(c,"debug",b)}else this.g+=b}};var Aa=h.console,H=function(a,b,c){if(a[b])a[b](c);else a.log(c)};
var I=function(){this.g=this.g;this.a=this.a};I.prototype.g=!1;I.prototype.s=function(){this.g||(this.g=!0,this.c())};I.prototype.c=function(){if(this.a)for(;this.a.length;)this.a.shift()()};var Ba=function(a){a&&"function"==typeof a.s&&a.s()};ma();ma();var J=function(a,b){this.type=a;this.target=b};J.prototype.a=function(){};var K=function(a){J.call(this,a?a.type:"");this.c=this.state=this.target=null;a&&(this.type=a.type,this.target=a.target||a.srcElement,this.state=a.state,this.c=a,a.defaultPrevented&&this.a())};n(K,J);K.prototype.a=function(){K.o.a.call(this);var a=this.c;a.preventDefault?a.preventDefault():a.returnValue=!1};
var L="closure_listenable_"+(1E6*Math.random()|0),Ca=0;var Ea=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.c=!!d;this.a=e;this.v=++Ca;this.removed=this.m=!1},M=function(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.a=null};var N=function(a){this.src=a;this.a={};this.c=0},Fa=function(a,b,c,d,e){var f=b.toString();b=a.a[f];b||(b=a.a[f]=[],a.c++);var g=O(b,c,d,e);-1<g?(a=b[g],a.m=!1):(a=new Ea(c,a.src,f,!!d,e),a.m=!1,b.push(a));return a};N.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=O(e,b,c,d);return-1<b?(M(e[b]),q.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.c--),!0):!1};
var Ga=function(a,b){var c=b.type,d;if(d=c in a.a){d=a.a[c];var e;e=q.indexOf.call(d,b,void 0);var f;(f=0<=e)&&q.splice.call(d,e,1);d=f}d&&(M(b),0==a.a[c].length&&(delete a.a[c],a.c--))};N.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,M(d[e]);delete this.a[c];this.c--}return b}; var P=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=O(a,c,d,e));return-1<b?a[b]:null},O=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.listener==b&&f.c==!!c&&f.a==d)return e}return-1};
var Q="closure_lm_"+(1E6*Math.random()|0),R={},Ha=0,S=function(a,b,c,d,e){if("array"==k(b)){for(var f=0;f<b.length;f++)S(a,b[f],c,d,e);return null}c=T(c);if(a&&a[L])a=a.listen(b,c,d,e);else{if(!b)throw Error("Invalid event type");var f=!!d,g=U(a);g||(a[Q]=g=new N(a));c=Fa(g,b,c,d,e);if(!c.proxy){d=Ia();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)a.addEventListener(b.toString(),d,f);else if(a.attachEvent)a.attachEvent(Ja(b.toString()),d);else throw Error("addEventListener and attachEvent are unavailable.");
Ha++}a=c}return a},Ia=function(){var a=Ka,b=function(c){return a.call(b.src,b.listener,c)};return b},La=function(a,b,c,d,e){if("array"==k(b))for(var f=0;f<b.length;f++)La(a,b[f],c,d,e);else c=T(c),a&&a[L]?a.unlisten(b,c,d,e):a&&(a=U(a))&&(b=P(a,b,c,!!d,e))&&V(b)},V=function(a){if("number"!=typeof a&&a&&!a.removed){var b=a.src;if(b&&b[L])Ga(b.l,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.c):b.detachEvent&&b.detachEvent(Ja(c),d);Ha--;(c=U(b))?(Ga(c,a),0==c.c&&(c.src=
null,b[Q]=null)):M(a)}}},Ja=function(a){return a in R?R[a]:R[a]="on"+a},Ka=function(a,b){var c;if(a.removed)c=!0;else{c=new K(b);var d=a.listener,e=a.a||a.src;a.m&&V(a);c=d.call(e,c)}return c},U=function(a){a=a[Q];return a instanceof N?a:null},Ma="__closure_events_fn_"+(1E9*Math.random()>>>0),T=function(a){if("function"==k(a))return a;a[Ma]||(a[Ma]=function(b){return a.handleEvent(b)});return a[Ma]};
var W=function(a){I.call(this);this.i=a;this.h={}};n(W,I);var Na=[];W.prototype.listen=function(a,b,c,d){"array"!=k(b)&&(b&&(Na[0]=b.toString()),b=Na);for(var e=0;e<b.length;e++){var f=S(a,b[e],c||this.handleEvent,d||!1,this.i||this);if(!f)break;this.h[f.v]=f}return this};
W.prototype.unlisten=function(a,b,c,d,e){if("array"==k(b))for(var f=0;f<b.length;f++)this.unlisten(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.i||this,c=T(c),d=!!d,b=a&&a[L]?P(a.l,String(b),c,d,e):a?(a=U(a))?P(a,b,c,d,e):null:null,b&&(V(b),delete this.h[b.v]);return this};W.prototype.removeAll=function(){ga(this.h,function(a,b){this.h.hasOwnProperty(b)&&V(a)},this);this.h={}};W.prototype.c=function(){W.o.c.call(this);this.removeAll()}; W.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};
var X=function(){I.call(this);this.l=new N(this)};n(X,I);X.prototype[L]=!0;X.prototype.addEventListener=function(a,b,c,d){S(this,a,b,c,d)};X.prototype.removeEventListener=function(a,b,c,d){La(this,a,b,c,d)};X.prototype.c=function(){X.o.c.call(this);this.l&&this.l.removeAll(void 0)};X.prototype.listen=function(a,b,c,d){return Fa(this.l,String(a),b,c,d)};X.prototype.unlisten=function(a,b,c,d){return this.l.remove(String(a),b,c,d)};
var Y=function(){X.call(this);var a=document;this.w=a.getElementById("gws");this.h=a.getElementById("save_and_exit");this.h.disabled=!0;this.A=new D(chrome.storage.sync);this.i=new W(this);a=ca(Ba,this.i);this.g?a.call(void 0):(this.a||(this.a=[]),this.a.push(a))};n(Y,X);Y.c=function(){return Y.a?Y.a:Y.a=new Y};var Oa=new za;0!=Oa.c&&(ua(),Oa.c=!1);var Pa=C("image.collections.extension.Options");Y.prototype.D=function(a){this.w.value=a["stars-gws"]};
Y.prototype.C=function(){this.A.set({"stars-gws":this.w.value});this.h.disabled=!0;chrome.runtime.reload()};Y.prototype.B=function(){this.h.disabled=!1};var Z=Y.c();Pa&&Pa.log(ra,"Initializing extension options",void 0);Z.i.listen(Z.h,"click",Z.C).listen(document.body,"input",Z.B);var Qa={F:"stars-gws",G:"stars-last-import-time"},Ra=[],Sa=0,Ta;for(Ta in Qa)Ra[Sa++]=Qa[Ta];Z.A.get(Ra,l(Z.D,Z));

}catch(e){_DumpException(e)}
// Google Inc.
